### ISSUE TITLE
Support http authentication through the url

### ISSUE THREAD

**Issue by Mowd** [gregoiresage/pebble-image-viewer#2]
I have a web cam use http authentication to login.
Therefore I can simply access the cam image through the url like this:
http://user:password@example.com:8080/video.jpg
But somehow I can't load the image through the image viewer.
Can this be done in the app?

**Comment by gregoiresage** [comment]
If you can see the image in your browser, it should work in the app.
But someone has a problem with a jpeg the app couldn't decode. Can you send me an exmaple of a jpeg you want to display ?

**Comment by Mowd** [comment]
Original image is here:
http://mowd.tw/video.jpg
You're right, it could be the jpg problem, because even I try to load image from this url, it still return Error: Timeout.

**Comment by gregoiresage** [comment]
Fixed in 2.3

**Comment by Mowd** [comment]
Thanks you, now I can load this jpg without Timeout problem.
But I still can't load this jpg through the url schema like: http://user:password@example.com:8080/video.jpg
